### ISSUE TITLE
Smooth Scrolling with Multiple Div's

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-term-project#1]
$('.nav-items').localScroll();
$('.button').localScroll();

Will not allow me to add smooth scroll to two different div's

@thomasjbradley

**Comment by thomasjbradley** [comment]
Where is the `.button` class? Is it on something that surrounds the `a` tag?

**Comment by valeriebordeleau** [comment]
<a href="#bottom"><img src="artwork/button.svg" alt="down button" class="button island"></a>

**Comment by valeriebordeleau** [comment]
`<a href="#bottom"><img src="artwork/button.svg" alt="down button" class="button island"></a>`

**Comment by thomasjbradley** [comment]
The class that `localScroll()` targets should be on a parent element of the `<a>` for Local Scroll to work properly.

**Comment by valeriebordeleau** [comment]
`$('.button2').localScroll();`
`<a href="#bottom" class="button2"><img src="artwork/button.svg" alt="down button" class="button island"></a>` 

Is still not working

**Comment by valeriebordeleau** [comment]
Misunderstood. Everything is fixed. Thank-you
