### ISSUE TITLE
banner animations stopped functioning

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-term-project#4]
@thomasjbradley

Made no changes to banner, all animations (sun rotation, clouds hovering, toggle sliding open) stopped working in firefox browser

**Comment by thomasjbradley** [comment]
Have you tried validating the CSS?

**Comment by valeriebordeleau** [comment]
Just validated code both CSS & HTML, still not responding

**Comment by thomasjbradley** [comment]
Here's one that got missed:
https://github.com/valeriebordeleau/dsn1676-term-project/blob/gh-pages/css/general.css#L307

**Comment by valeriebordeleau** [comment]
Thanks. Though that only affects my svg. It's not connected to my banner in any way.

**Comment by thomasjbradley** [comment]
Does that fix it though?

**Comment by valeriebordeleau** [comment]
Was the only issue with that line of code the missing `@-webkit-` because that didn't fix the banner?

**Comment by thomasjbradley** [comment]
There was missing curly braces at that point.

**Comment by valeriebordeleau** [comment]
I believe I closed all the curly braces, it's still not animating

**Comment by valeriebordeleau** [comment]
Animation are working found another missing brace thanks.
